### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by thecodechaser** [patriciachrysy/javascript-to-do-list#4]
Feedback, suggestions, improvements.

**Comment by thecodechaser** [comment]
Hello,@patriciachrysy 👋 

You did great so far, Your project is already looking great, You probably did hard work for this 👍. 

### To highlight 💯 

- Your code is clean.
- Your code is up to the mark with ES6.
- The drag and drop functionality is impressive.

Great job 👍

**Comment by Debas-31** [comment]
Good Job, @patriciachrysy  💯 
Your code is so clean

**Comment by patriciachrysy** [comment]
Thank you guys for the feedback !!!
